// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSOdPU0dUIeQP60sDA7YbOlKFoYNJtwy0',
    appId: '1:1098938022114:web:24e75ae51af0ae971886bb',
    messagingSenderId: '1098938022114',
    projectId: 'rentandreturn-d55d5',
    authDomain: 'rentandreturn-d55d5.firebaseapp.com',
    storageBucket: 'rentandreturn-d55d5.firebasestorage.app',
    measurementId: 'G-6JWT8F8MF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc2J9F08bMi2palY0HRkGaVoZEtzDgAy0',
    appId: '1:1098938022114:android:2f466ea9a123adf91886bb',
    messagingSenderId: '1098938022114',
    projectId: 'rentandreturn-d55d5',
    storageBucket: 'rentandreturn-d55d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TK3NDX7r78m_8ovBmkqGMwvrqOYf4lc',
    appId: '1:1098938022114:ios:0e2e45a0558aceee1886bb',
    messagingSenderId: '1098938022114',
    projectId: 'rentandreturn-d55d5',
    storageBucket: 'rentandreturn-d55d5.firebasestorage.app',
    iosBundleId: 'com.example.rentAndReturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3TK3NDX7r78m_8ovBmkqGMwvrqOYf4lc',
    appId: '1:1098938022114:ios:0e2e45a0558aceee1886bb',
    messagingSenderId: '1098938022114',
    projectId: 'rentandreturn-d55d5',
    storageBucket: 'rentandreturn-d55d5.firebasestorage.app',
    iosBundleId: 'com.example.rentAndReturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSOdPU0dUIeQP60sDA7YbOlKFoYNJtwy0',
    appId: '1:1098938022114:web:5372de4c73f6c5011886bb',
    messagingSenderId: '1098938022114',
    projectId: 'rentandreturn-d55d5',
    authDomain: 'rentandreturn-d55d5.firebaseapp.com',
    storageBucket: 'rentandreturn-d55d5.firebasestorage.app',
    measurementId: 'G-MVPRBM5VPF',
  );
}
